# Generated by Django 3.2 on 2022-08-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maker',
            old_name='type',
            new_name='maker',
        ),
    ]
