# Generated by Django 3.2 on 2022-09-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_vehicle_available_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='maker',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
