# Generated by Django 3.2 on 2022-09-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_tradein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradein',
            name='user',
        ),
        migrations.AddField(
            model_name='tradein',
            name='year',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
