# Generated by Django 3.2 on 2022-09-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20220918_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tradein',
        ),
    ]
