# Generated by Django 3.2 on 2022-09-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_tradein'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradein',
            name='condition',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tradein',
            name='full_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tradein',
            name='manufacturer',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tradein',
            name='mod',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tradein',
            name='odo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tradein',
            name='trade_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
