# Generated by Django 3.2 on 2022-09-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20220918_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradein',
            name='user',
            field=models.CharField(default='', max_length=25),
        ),
    ]
