# Generated by Django 3.2 on 2022-09-18 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_tradein'),
        ('checkout', '0002_auto_20220818_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trade_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.tradein'),
        ),
    ]
