# Generated by Django 3.2 on 2022-09-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_trade_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trade_in',
        ),
    ]
