# Generated by Django 3.2 on 2022-09-18 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_tradein'),
        ('checkout', '0004_remove_order_trade_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trade_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradein', to='stock.tradein'),
        ),
    ]
